### ISSUE TITLE
Question about ColorChecker RECommended (2018) dataset.

### ISSUE THREAD

**Issue by YuxiangTang** [QiuJueqin/Reweight-CC#3]
Hi,
I am confused that the dataset you mentioned in training phase.
the training set is：Color-checker (by Shi) (2010)
but gt is: ColorChecker RECommended (2018)
why not use re-processing images  from ColorChecker RECommended (2018) dataset?

and I really wanna know how to use the ColorChecker RECommended (2018) dataset, because the re-processing images looks very dark.
thanks.

**Comment by QiuJueqin** [comment]
@YuxiangTang If I remember correctly, the GTs from RECommended can be directly applied to images in Shi's dataset. It's expected that images look dark since they are linear images without tone-mapping or gamma-correction.

**Comment by YuxiangTang** [comment]
Thx.
